/*
 * server/controllers/api/users.js
 */

'use strict';

// Controllers are auto-generated by `restify.model`.
// Uncomment the following code to override controller.

// function LIST(req, cb) {
//   cb(new Error('Not yet implemented.'));
// }

// function GET(req, id, cb) {
//   cb(new Error('Not yet implemented.'));
// }

// function POST(req, cb) {
//   cb(new Error('Not yet implemented.'));
// }

// function PUT(req, id, cb) {
//   cb(new Error('Not yet implemented.'));
// }

// function DELETE(req, id, cb) {
//   cb(new Error('Not yet implemented.'));
// }

// Public API
// exports.LIST = LIST;
// exports.GET = GET;
// exports.POST = POST;
// exports.PUT = PUT;
// exports.DELETE = DELETE;
